# Generated by Django 2.2 on 2019-04-11 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0002_subredditstoread'),
    ]

    operations = [
        migrations.AddField(
            model_name='subredditstoread',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subredditstoread',
            name='post_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='from_subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_post', to='goodnewsbot_worker.SubredditsToRead'),
        ),
    ]
