# Generated by Django 2.2 on 2019-04-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0003_auto_20190411_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='permalink',
            field=models.CharField(default='Fake', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_url',
            field=models.CharField(max_length=2000),
        ),
    ]
