# Generated by Django 2.2 on 2019-04-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0004_auto_20190415_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='permalink',
            field=models.CharField(max_length=128),
        ),
    ]
