# Generated by Django 2.2 on 2019-04-15 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0005_auto_20190415_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=10, unique=True)),
                ('cutoff', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='analysed_sentiment2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_post', to='goodnewsbot_worker.Sentiment'),
        ),
    ]
