# Generated by Django 2.2 on 2019-04-15 22:29

from django.db import migrations


def populate_sentiment_model(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    sentiment_model = apps.get_model('goodnewsbot_worker', 'Sentiment')
    sentiments = {
        "POSITIVE": 0.75,
        "NEGATIVE": 0.75,
        "NEUTRAL": 0.75,
        "MIXED": 0.75,
    }
    for sentiment, cutoff in sentiments.items():
        (
            sentiment_model
            .objects
            .using(db_alias)
            .create(
                sentiment=sentiment,
                cutoff=cutoff,
            )
        )


def fk_news_post_to_sentiments(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    sentiment_model = apps.get_model('goodnewsbot_worker', 'Sentiment')
    news_model = apps.get_model('goodnewsbot_worker', 'NewsPost')
    for sentiment in sentiment_model.objects.using(db_alias).all():
        (
            news_model
            .objects
            .using(db_alias)
            .filter(analysed_sentiment=sentiment.sentiment)
            .update(analysed_sentiment2=sentiment)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0006_auto_20190415_2227'),
    ]

    operations = [
        migrations.RunPython(
            populate_sentiment_model,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            fk_news_post_to_sentiments,
            migrations.RunPython.noop,
        ),
    ]
