# Generated by Django 2.2 on 2019-05-02 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0007_auto_20190415_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSToRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField()),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantified_positive', models.DecimalField(blank=True, decimal_places=19, max_digits=21, null=True)),
                ('quantified_negative', models.DecimalField(blank=True, decimal_places=19, max_digits=21, null=True)),
                ('quantified_neutral', models.DecimalField(blank=True, decimal_places=19, max_digits=21, null=True)),
                ('quantified_mixed', models.DecimalField(blank=True, decimal_places=19, max_digits=21, null=True)),
                ('title_as_posted', models.CharField(max_length=300, null=True, verbose_name="Reddit Post Title (may need to have been shortened to fit Reddit's 300 char link post title limit)")),
                ('analysed_sentiment2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='goodnewsbot_worker.Sentiment')),
                ('our_post_permalink', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubredditsToPostTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='analysed_sentiment',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='analysed_sentiment2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goodnewsbot_worker.Sentiment'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='from_subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goodnewsbot_worker.SubredditsToRead'),
        ),
        migrations.CreateModel(
            name='RSSPost',
            fields=[
                ('sentimentanalysis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goodnewsbot_worker.SentimentAnalysis')),
                ('title', models.CharField(max_length=512)),
                ('story_body', models.TextField(null=True)),
                ('story_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('goodnewsbot_worker.sentimentanalysis',),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='subreddit_posted_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='goodnewsbot_worker.SubredditsToPostTo'),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='subreddit_to_post_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentiment', to='goodnewsbot_worker.SubredditsToPostTo'),
        ),
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('sentimentanalysis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goodnewsbot_worker.SentimentAnalysis')),
                ('post_title', models.CharField(max_length=300)),
                ('post_url', models.CharField(max_length=2000)),
                ('their_post_permalink', models.CharField(max_length=128)),
                ('from_subreddit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reddit_post', to='goodnewsbot_worker.SubredditsToRead')),
            ],
            options={
                'abstract': False,
            },
            bases=('goodnewsbot_worker.sentimentanalysis',),
        ),
    ]
