# Generated by Django 2.2 on 2019-05-02 13:32

from django.db import migrations


def populate_new_news_story_url_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    subreddit_to_post_to_model = apps.get_model('goodnewsbot_worker', 'RedditPost')
    for rp in subreddit_to_post_to_model.objects.using(db_alias).all():
        rp.news_story_url = rp.post_url
        rp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0011_sentimentanalysis_news_story_url'),
    ]

    operations = [
        migrations.RunPython(
            populate_new_news_story_url_field,
            migrations.RunPython.noop,
            atomic=True,
            elidable=True,
        ),
    ]
