# Generated by Django 2.2 on 2019-05-06 19:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0014_auto_20190506_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsspost',
            name='description_analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsspost',
            name='title_analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsspost',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
