# Generated by Django 2.2 on 2019-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnewsbot_worker', '0015_add_fields_to_rsspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsstoread',
            name='can_handle_https_story_urls',
            field=models.BooleanField(default=True, verbose_name="Should we prepend https:// to this news source's story urls?"),
        ),
    ]
